### ISSUE TITLE
script for ubuntu 18.04 to compile Windows 32 and 64 bit EXE's

### ISSUE THREAD

**Issue by E-x-E** [E-x-E/Exe#1]
**Exe**
#I want a script for ubuntu 18.04 that will install everything needed, 
#so I can compile Windows 32 and 64 bit EXE's from Bitcoin-qt Github repos.

#Needs to be everything in 1 script. 
#Can be used on Any NEW BASIC INSTALL of UBUNTU 18.04
#example: Used on a Digital-Oceans, Vultr, Rando vps instance of U18.04 
#Will Use https://github.com/neutroncoin/neutron.git repo to test build Windows EXE 
#of GUI & Daemon wallet.

**Comment by ryu0** [comment]
I am considering writing such a script, but your problem description is lacking details. It appears you are asking for a script to setup a cross-compiling environment on Ubuntu 18.04, but I need to know what software you intend to cross-compile, as I need to know what software dependencies I will need to deal with.

**Comment by E-x-E** [comment]
The program I would like to compile is a coin wallet from Neutroncoin. 
#Will Use https://github.com/neutroncoin/neutron.git repo to test build Windows EXE
It will be the GUI WALLET "Neutron-qt" from the above repo for windows 32 or 64. As far as the actually dependencies, I honestly don't know what they are using. How can we check to see what they are using? there is a DOC file in the repo that has some info i think can be a start. 
https://github.com/neutroncoin/neutron/tree/master/doc
Thanks for your time! 
Bounty is still open for anyone to claim: 
https://www.bountysource.com/issues/58462716-script-for-ubuntu-18-04-to-compile-windows-32-and-64-bit-exe-s

**Comment by surajmandalcell** [comment]
Can your script involve GUI interactions during installations?
Reason : The qt version used in https://github.com/neutroncoin/neutron.git is older and not available via default repositories so if you try to install build using latest version of qt available in default repositories it'll throw too many errors to handle.
Solution : Using archived `.run` binaries  in script and expect user to install qt graphically.
After then the build can run normally and can generate exe files for windows.  
GUI interaction im talking about :
![image](https://user-images.githubusercontent.com/11650177/40754099-11f207d4-6495-11e8-9a02-41065c463758.png)

**Comment by oicu8** [comment]
----------------------------------
# Compile for Windows Executable (using Ubuntu 18.04)
-----------------------------------

> sudo apt-get install g++-mingw-w64-i686 mingw-w64-i686-dev

#---START MXE Setup--- 

# Get MXE

> MXE_PATH=~/dependencies/mxe_20171031
> MXE_COMMIT=23f32e0944ed2f618ce6a15a7f048686ff896483 ; # 2017-10-31 - https://github.com/mxe/mxe/tree/23f32e0944ed2f618ce6a15a7f048686ff896483
> mkdir -p $MXE_PATH
> cd $MXE_PATH
> ###git clone --depth 1 --branch master https://github.com/mxe/mxe.git $MXE_PATH
> git clone --branch master https://github.com/mxe/mxe.git $MXE_PATH
> cd $MXE_PATH
> ###git checkout $MXE_COMMIT .
> git checkout --detach $MXE_COMMIT

# [Optional] Allocate more memory for compile

> sudo dd if=/dev/zero of=/var/swap.img bs=1024k count=1000
> sudo mkswap /var/swap.img
> sudo chmod 600 /var/swap.img
> sudo swapon /var/swap.img

# Install MXE dependencies

> $MXE_PATH/tools/install-deps


# Compile reference: http://www.cs.cmu.edu/~soonhok/mxe-cross-compile-windows-binaries-on-ubuntu.htm
MXE_TARGETS [MinGW-w64 targets]: i686-w64-mingw32 (32-bit architecture), x86_64-w64-mingw32 (64-bit architecture)
 -j4 means up to four packages are built in parallel (inter-package)
 JOBS=4 allows four compiler processes to compile a package in parallel (intra-package)



> ARCH=x86_64-w64-mingw32.static.posix
> MXE_PATH=~/dependencies/mxe_20171031
> cd $MXE_PATH
> make MXE_TARGETS=$ARCH bzip2_URL=foo.org boost qttools miniupnpc libqrencode
> make MXE_TARGETS=$ARCH qttools
> make MXE_TARGETS=$ARCH miniupnpc
> make MXE_TARGETS=$ARCH libqrencode
> 

# Compile boost
###     MXE boost 1.60.0 - https://github.com/mxe/mxe/blob/23f32e0944ed2f618ce6a15a7f048686ff896483/src/boost.mk

> make MXE_TARGETS="i686-w64-mingw32.static" boost bzip2_URL=foo.org


    ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~

    Failed to build package boost for target i686-w64-mingw32.static!
    gcc.compile.c++ bin.v2/libs/log/build/gcc-mingw-mxe/release/abi-ms/binary-format-pe/link-static/target-os-windows/threadapi-win32/threading-multi/date_time_format_parser.o
    ...failed updating 1 target...
    ...updated 11311 targets...

    most likely just ran out of CPU and/or RAM, recompiling worked after freeing up some resources

    ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~

    Download failed or wrong checksum of package bzip2!
    ------------------------------------------------------------
    HTTP request sent, awaiting response... 200 OK
    Length: unspecified [text/html]
    Saving to: â€˜/root/dependencies/mxe_20171031/pkg/.tmp-bzip2-1.0.6.tar.gzâ€™
         0K .......... .......                                      111K=0.2s
    2018-10-25 15:09:50 (111 KB/s) - â€˜/root/dependencies/mxe_20171031/pkg/.tmp-bzip2-1.0.6.tar.gzâ€™ saved [17526]
    + cat /root/dependencies/mxe_20171031/pkg/.tmp-bzip2-1.0.6.tar.gz
    + rm /root/dependencies/mxe_20171031/pkg/.tmp-bzip2-1.0.6.tar.gz
    ------------------------------------------------------------
    [log]      /root/dependencies/mxe_20171031/log/bzip2-download

    Makefile:538: recipe for target 'download-only-bzip2-1.0.6.tar.gz' failed
    make: *** [download-only-bzip2-1.0.6.tar.gz] Error 1

    ---> https://github.com/mxe/mxe/issues/2176#issuecomment-412262320
        $ make MXE_TARGETS=x86_64-w64-mingw32.static.posix boost bzip2_URL=foo.org
            - doing this forces bzip2 to be downloaded from one of the backup mirrors

    ---> https://github.com/openscad/openscad/issues/2441
        - some interesting discussion here to look into regarding gcc 5/6/7 compiling...

    ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~


# Compile berkeley db
###     MXE db 6.1.26 - https://github.com/mxe/mxe/blob/23f32e0944ed2f618ce6a15a7f048686ff896483/src/db.mk
###     For BDB 4.8, need to build from source - https://bitcointalk.to/index.php?topic=1080289.0;all
# setup build paths

> ARCH=i686-w64-mingw32.static
> ARCH=x86_64-w64-mingw32.static.posix
> MXE_PATH=~/dependencies/mxe_20171031
> export PATH=$MXE_PATH/usr/bin:$PATH
> MXE_INCLUDE_PATH=$MXE_PATH/usr/$ARCH/include
> MXE_LIB_PATH=$MXE_PATH/usr/$ARCH/lib

# get source

> mkdir -p ~/compile/$ARCH
> cd ~/compile/$ARCH
> rm -rf berkeleydb
> mkdir berkeleydb
> cd berkeleydb
> wget http://download.oracle.com/berkeley-db/db-4.8.30.NC.tar.gz
> tar -xzvf db-4.8.30.NC.tar.gz

# configure build

> cd db-4.8.30.NC/build_windows/
> CC=$MXE_PATH/usr/bin/$ARCH-gcc \
> CXX=$MXE_PATH/usr/bin/$ARCH-g++ \
> ../dist/configure \
>     --disable-replication \
>     --enable-mingw \
>     --enable-cxx \
>     --host x86 \
>     --prefix=$MXE_PATH/usr/$ARCH
> 

# compile

> make ; make install


# Compile qt5
###  MXE qt5 - https://github.com/mxe/mxe/blob/23f32e0944ed2f618ce6a15a7f048686ff896483/src/qt5.mk

> ARCH=i686-w64-mingw32.static
> ARCH=x86_64-w64-mingw32.static.posix
> make MXE_TARGETS=$ARCH qttools
> # (maybe qtbase also???)
> 

# Compile miniupnpc
###     MXE miniupnpc 1.9 - https://github.com/mxe/mxe/blob/23f32e0944ed2f618ce6a15a7f048686ff896483/src/miniupnpc.mk

> ARCH=i686-w64-mingw32.static
> ARCH=x86_64-w64-mingw32.static.posix
> make MXE_TARGETS=$ARCH miniupnpc


# Compile libqrencode
###     MXE libqrencode 4.0.0 - https://github.com/mxe/mxe/blob/23f32e0944ed2f618ce6a15a7f048686ff896483/src/libqrencode.mk

> ARCH=i686-w64-mingw32.static
> ARCH=x86_64-w64-mingw32.static.posix
> make MXE_TARGETS=$ARCH libqrencode


#--- END MXE setup ---


# setup build paths

> ARCH=i686-w64-mingw32.static
> ARCH=x86_64-w64-mingw32.static.posix
> MXE_PATH=~/dependencies/mxe_20171031
> export PATH=$MXE_PATH/usr/bin:$PATH
> MXE_INCLUDE_PATH=$MXE_PATH/usr/$ARCH/include
> MXE_LIB_PATH=$MXE_PATH/usr/$ARCH/lib
> 
> RELEASE_TAG=master
> TARGET=windows
> cd ~
> rm -rf neutron_release_$RELEASE_TAG/build_$TARGET
> mkdir -p neutron_release_$RELEASE_TAG/build_$TARGET
> cd neutron_release_$RELEASE_TAG/build_$TARGET
> git clone -b $RELEASE_TAG https://github.com/neutroncoin/neutron.git
> cd neutron
> 

# [Optional] Allocate more memory for compile

> sudo dd if=/dev/zero of=/var/swap.img bs=1024k count=1000
> sudo mkswap /var/swap.img
> sudo chmod 600 /var/swap.img
> sudo swapon /var/swap.img
> 
> 

# generate makefile
     $ARCH-qmake-qt5 \
    BDB_INCLUDE_PATH=$MXE_INCLUDE_PATH \
    BDB_LIB_PATH=$MXE_LIB_PATH \
    BOOST_LIB_SUFFIX=-mt \
    BOOST_THREAD_LIB_SUFFIX=_win32-mt \
    BOOST_INCLUDE_PATH=$MXE_INCLUDE_PATH/boost \
    BOOST_LIB_PATH=$MXE_LIB_PATH \
    OPENSSL_INCLUDE_PATH=$MXE_INCLUDE_PATH/openssl \
    OPENSSL_LIB_PATH=$MXE_LIB_PATH \
    MINIUPNPC_INCLUDE_PATH=$MXE_INCLUDE_PATH \
    MINIUPNPC_LIB_PATH=$MXE_LIB_PATH \
    QRENCODE_INCLUDE_PATH=$MXE_INCLUDE_PATH \
    QRENCODE_LIB_PATH=$MXE_LIB_PATH \
    QMAKE_LRELEASE=$MXE_PATH/usr/$ARCH/qt5/bin/lrelease \
    \
    MXE=1 \
    USE_QRCODE=1 \
    USE_UPNP=1 \
    RELEASE=1 \
    USE_BUILD_INFO=1 \
    \
    neutron-qt.pro

# start compile

> make -f Makefile.Release


    IF error when running "i686-w64-mingw32.static-g++ ..."
        src/threadinterrupt.h:29:10: error: 'condition_variable' in namespace 'std' does not name a type
        --> https://github.com/dashpay/dash/issues/1751
                $ sudo update-alternatives --config i686-w64-mingw32-gcc
                (select i686-w64-mingw32-gcc-posix)
                $ sudo update-alternatives --config i686-w64-mingw32-g++
                (select i686-w64-mingw32-g++-posix)

                $ sudo update-alternatives --config i686-w64-mingw32-gcc
                    There are 2 choices for the alternative i686-w64-mingw32-gcc (providing /usr/bin/i686-w64-mingw32-gcc).

                      Selection    Path                                 Priority   Status
                    ------------------------------------------------------------
                    * 0            /usr/bin/i686-w64-mingw32-gcc-win32   60        auto mode
                      1            /usr/bin/i686-w64-mingw32-gcc-posix   30        manual mode
                      2            /usr/bin/i686-w64-mingw32-gcc-win32   60        manual mode

                    Press <enter> to keep the current choice[*], or type selection number: 1
                    update-alternatives: using /usr/bin/i686-w64-mingw32-gcc-posix to provide /usr/bin/i686-w64-mingw32-gcc (i686-w64-mingw32-gcc) in manual mode
                    update-alternatives: warning: skip creation of /usr/bin/i686-w64-mingw32-gcc-7 because associated file /usr/bin/i686-w64-mingw32-gcc-7.2-posix (of link group i686-w64-mingw32-gcc) doesn't exist
                $ sudo update-alternatives --config i686-w64-mingw32-g++
                    There are 2 choices for the alternative i686-w64-mingw32-g++ (providing /usr/bin/i686-w64-mingw32-g++).

                      Selection    Path                                 Priority   Status
                    ------------------------------------------------------------
                    * 0            /usr/bin/i686-w64-mingw32-g++-win32   60        auto mode
                      1            /usr/bin/i686-w64-mingw32-g++-posix   30        manual mode
                      2            /usr/bin/i686-w64-mingw32-g++-win32   60        manual mode

                    Press <enter> to keep the current choice[*], or type selection number: 1
                    update-alternatives: using /usr/bin/i686-w64-mingw32-g++-posix to provide /usr/bin/i686-w64-mingw32-g++ (i686-w64-mingw32-g++) in manual mode
